# Generated by Django 5.2 on 2025-05-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-created',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='book',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='books/secondary/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='books/secondary/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='books/secondary/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/main/'),
        ),
    ]
